trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: Build and package tasks
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/CreateAllPackages.bat'

- task: CopyFiles@2
  displayName: Copy aab result files
  inputs:
    contents: '*.vsix'
    targetFolder: '$(build.artifactStagingDirectory)'